### ISSUE TITLE
Script died after server rebooted

### ISSUE THREAD

**Issue by Cyinthia** [davidmcclelland/notifications-of-avabur#21]
Probably core code rewrite somewhere that made the script non-functional.

**Comment by davidmcclelland** [comment]
Interesting, the script works just fine for me on beta and live. What version of the script are you running? What OS/browser/etc? Feel free to message me in-game too - username is WinterPhoenix

**Comment by Cyinthia** [comment]
Version 63.0.3239.132 (Official Build) (64-bit) Chrome 1.5.2.1

**Comment by davidmcclelland** [comment]
If you refresh your tab does it load correctly? Sometimes tampermonkey seems to have issues with loading resources from the internet, and refreshing seems to solve the issue.

**Comment by Cyinthia** [comment]
yea tried that

**Comment by davidmcclelland** [comment]
join the AvaNotifications channel if you're still online, I'll help you figure it out

**Comment by Cyinthia** [comment]
[Violation] Forced reflow while executing JavaScript took 46ms

Followed by a spammage of

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

then

[Violation] 'DOMContentLoaded' handler took 913ms
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input id=​"current_password_ef" name=​"current_email_ef" type=​"password">​
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input id=​"current_password" name=​"current_password" type=​"password">​
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input id=​"new_password" name=​"new_password" type=​"password">​
game.php:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input id=​"new_password_confirm" name=​"new_password_confirm" type=​"password">​
[Violation] Forced reflow while executing JavaScript took 50ms
jquery-1.11.2.min.js:3 GET https://www.avabur.com/css/images/ui-icons_222222_256x240.png 404 ()
Jb @ jquery-1.11.2.min.js:3
css @ jquery-1.11.2.min.js:3
U @ jquery-1.11.2.min.js:3
Vb @ jquery-1.11.2.min.js:3
show @ jquery-1.11.2.min.js:3
m.fn.(anonymous function) @ jquery-1.11.2.min.js:4
$.fn.extend.show @ jquery-ui.js:678
_renderAxis @ jquery-ui.js:460
_create @ jquery-ui.js:462
(anonymous) @ jquery-ui.js:22
_createWidget @ jquery-ui.js:29
$.(anonymous function).(anonymous function) @ jquery-ui.js:21
(anonymous) @ jquery-ui.js:27
each @ jquery-1.11.2.min.js:2
each @ jquery-1.11.2.min.js:2
$.fn.(anonymous function) @ jquery-ui.js:27
(anonymous) @ js.js?t=1514120488:7
j @ jquery-1.11.2.min.js:2
fireWith @ jquery-1.11.2.min.js:2
ready @ jquery-1.11.2.min.js:2
J @ jquery-1.11.2.min.js:2

Then followed by a spammage of till the end of the console

jquery-1.11.2.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by Cyinthia** [comment]
fixed with chrome restart
